version: '3.7'
services:
  app:
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA
    ports:
      - "5000:5000"
  test:
    image: curlimages/curl:7.73.0
    command: /bin/sh -c "sleep 10 && curl -s http://app:5000/ -i -vvv"
