---
# Default values for flask-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image: https://registry.gitlab.com/s045724/flask-app/main
imageTag: 56c5fe8f
imagePullSecret: cicd-gitlab-registry

ingress:
  host: flask-app.lvh.me

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
